spring:
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/springboot
      username: postgres
      password: pass
      driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/springboot
      username: postgres
      password: pass
      driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always
